namespace mtgalib.Server
{
    public enum GameServerErrorCode
    {
        ParseError = -32700,
        InvalidRequest = -32600,
        MethodNotFound = -32601,
        InvalidParams = -32602,
        InternalError = -32603,
        OldFormatError = -32001,
        FD_ClientNotAuthenticated = 1000,
        FD_InvalidClientVersion,
        FD_AlreadyConnected,
        FD_AuthError,
        FD_AuthFailed,
        FD_AccessDenied,
        FD_SystemDown,
        FD_MsgTooLarge,
        Progression_InvalidTrackDefinition = 2000,
        Progression_TrackDisabled,
        Progression_RewardWebDisabled,
        Progression_NodeUnlockFailed,
        Progression_NodeUnlockFailed_NotEnoughOrbs,
        Progression_NodeUnlockFailed_MetricUnlockOnly,
        Progression_InvalidTrackProgress,
        Deck_DeckNotFound = 3000,
        Mercantile_ProductNotFound = 4000,
        Mercantile_ProductNotActive,
        Mercantile_InvalidQuantity,
        Mercantile_PurchaseLimitReached,
        Mercantile_StoreNotEnabled,
        PlayerInventory_NotEnoughGold = 5000,
        PlayerInventory_NotEnoughGems,
        PlayerInventory_MustUseGoldOrGems,
        PlayerInventory_MustHaveNegativeCost,
        PlayerInventory_VoucherNotAvailable,
        Event_CannotGetActiveEvents = 6000,
        Event_CannotModifyWinLossRecord,
        Event_CannotEvaluatePayouts,
        Event_CannotGetCourses,
        Event_CannotGetCourse,
        Event_EventNotFoundOrDoesntUseCourses = 6012,
        Event_CannotJoinEvent = 6005,
        Event_EventIsDisabled,
        Event_EventIsLocked,
        Event_NoRoleToJoinWith,
        Event_CannotCreateCourseDuringJoin,
        Event_HasNoCourse,
        Event_CannotSaveCourse,
        Event_CannotPayEntry = 6013,
        Event_ImproperDeckDataFormat,
        Event_DeckAlreadySubmitted,
        Event_PlayerNotReadyToMatch,
        Event_CannotJoinMatchmakingQueue,
        Event_CannotDropFromEvent,
        Event_PlayerUnexpectedStatePreventsDraftStart,
        Event_CannotStartDraft,
        Event_PlayerUnexpectedStatePreventsDraftComplete,
        Event_CannotCompleteDraft,
        Event_NeedMoreMatchesBeforeClaimPrize,
        Event_CannotClaimPrize,
        Event_PrematchConditionsUnmet,
        Event_CannotClaimNoGateRewards,
        Event_CanNotStartDirectChallenge,
        Event_CanNotStartAIBotMatch,
        Event_CourseChoicesUndetermined,
        Event_CannotGetChoices,
        Event_CannotMakeChoice,
        Event_DeckValidation_General = 6900,
        Event_DeckValidation_TooLarge,
        Event_DeckValidation_MainIllegalCardQuantity,
        Event_DeckValidation_SideboardIllegalCardQuantity,
        Event_DeckValidation_CardNotInPool,
        Event_DeckValidation_EmergencyBannedCard
    }
}